puts "🌱 Seeding spices..."

# Seed your database here
# Book.create(name: "Where the Wild Things Are" , author: "Maurice Sendak", description:"The adventure that has inspired generations of children to let out their inner monsters, showing how imagination allows for an escape from life’s doldrums. It’s also a moving testament to family love, when young Max returns from his reverie, his mother has saved him a hot dinner." , imgurl: "https://api.time.com/wp-content/uploads/2014/09/01-best-childrens-books-where-the-wild-things-are1.jpg?quality=85&w=624" )
# Book.create(name:"The Snowy Day", author:"Ezra Jack Keats.", description: "The journey of Peter through a snowbound New York City made for a milestone: as a successful children’s story focused on a black protagonist, it broke down barriers many white editors may have never noticed. But Keats’ book is memorable too for the sheer beauty of its collage illustrations.", imgurl: " https://api.time.com/wp-content/uploads/2014/09/02-best-childrens-books-the-snowy-day.jpg?quality=85&w=723")
# Book.create(name:"Goodnight Moon,", author:"Margaret Wise Brown", description:"Somewhere a child is being put to sleep right now to Brown’s soothing, repetitive cadences. While the lines may be etched in every parent’s memory, Hurd’s illustrations, with their quirky hidden jokes, provide amusement on the thousandth reading." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/03-best-childrens-books-goodnight-moon.jpg?quality=85&w=660")
# Book.create(name:"Blueberries for Sal", author:"Robert McCloskey", description:"The block-printed illustrations show just how similar families of different species can be, as child Sal and a baby bear covet Maine blueberries on a berry hunt with their respective mothers. It’s an instructive read for any kid who’s ever felt a bit like a wild animal, or parents who’ve ever felt like they’re raising one." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/04-best-childrens-books-blueberries-for-sal.jpg?quality=85&w=759")
# Book.create(name:"Little Bear (series)", author:"Else Holmelund Minarek", description:"Minarik wrote these stories, which convey a young cub’s yearning for his absent father, but it’s Sendak’s illustrations that catch the eye and allow for endless imaginings of life among woodland critters." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/05-best-childrens-books-little-bear.jpg?quality=85&w=354")
# Book.create(name:"Owl Moon", author:"Jane Yolen", description:"Many young bird watchers likely owe their passion to this story of a father-daughter trip to find the elusive great horned owl takes flight thanks to Schoenherr’s evocative woods-at-night illustrations" , imgurl:"https://api.time.com/wp-content/uploads/2014/09/07-best-childrens-books-owl-moon.jpg?quality=85&w=421")
# Book.create(name:"The Giving Tree", author:"Shel Silverstein.", description:"It’s hard to imagine a story more poignant than the tale of a tree that gives its life for a boy turned self-centered young man. It’s been interpreted along environmentalist and religious lines, but all can agree on the beauty of its underlying theme of generosity." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/08-best-childrens-books-the-giving-tree1.jpg?quality=85&w=446")
# Book.create(name:"Tuesday", author:"David Wiesner", description:"Who needs text? Not this illustrator, who also “wrote” the very few words that make up his tale. His stunning, propulsive watercolors show flying frogs on a surreal adventure. Reading may be fundamental, but here the pictures do almost all the talking." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/11-best-childrens-books-tuesday.jpg?quality=85&w=525")
# Book.create(name:"Where the Sidewalk Ends", author:"Shel Silverstein", description:"Silverstein wasn’t just good at tales of leafy self-sacrifice. His loopy poems have been speaking to kids’ concerns and sparking their imaginations for decades. Any child who’s ever fantasized about playing “hug o’ war” instead of tug-of-war will find a kindred spirit in these pages." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/12-best-childrens-books-where-the-sidewalk-ends.jpg?quality=85&w=434")
# Book.create(name:"Harold and the Purple Crayon", author:" Crockett Johnson", description:"A creative boy crafts entire worlds of his own devising, using only his trusty crayon." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/18-best-childrens-books-harold-and-the-purple-crayon1.jpg?quality=85&w=447")
# Book.create(name:"Make Way for Ducklings,", author:"Robert McCloskey", description:"A loving mother duck ferries her eight young ones through Boston" , imgurl:"https://api.time.com/wp-content/uploads/2014/09/06-best-childrens-books-make-way-for-ducklings.jpg?quality=85&w=434")
# Book.create(name:"Olivia,", author:" Ian Falconer", description:"Minimalist charcoal illustrations enrich the quietly funny narrative about a confident little pig." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/22-best-childrens-books-olivia.jpg?quality=85&w=421")
# Book.create(name:"Madeline (series)", author:"Ludwig Bemelmans", description:"A spunky French girl navigates boarding school and the removal of her appendix with confidence and poise." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/20-best-childrens-books-madeline.jpg?quality=85&w=407")
# Book.create(name:"Anno's Journey,", author:"Mitsumasa Anno.", description:"This visual feast doesn't need a single word to showcase the beauty of northern Europe." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/14-best-childrens-books-annos-journey.jpg?quality=85&w=462")
# Book.create(name:"Frog and Toad (series)", author:"Arnold Lobel", description:"Two inseparable best friends keep each other company during all their adventures." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/17-best-childrens-books-frog-and-toad.jpg?quality=85&w=376")
# Book.create(name:"The Story of Ferdinand", author:"Munro Leaf", description:"Contrary to the stereotype of his species, Ferdinand is a calm, peaceful bull who likes to relax under the cork tree." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/25-best-childrens-books-the-story-of-ferdinand1.jpg?quality=85&w=457")
# Book.create(name:"Don't Let the Pigeon Drive the Bus", author:"Mo Williams.", description:"One stubborn pigeon refuses to give up on his bird-brained dream of driving a vehicle." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/16-best-childrens-books-dont-let-the-pigeon-drive-the-bus.jpg?quality=85&w=561")
# Book.create(name:"The Lorax", author:"Dr. Seuss", description:"Seuss takes on serious subject matter without compromising his playful style in this environmentalist fable." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/84-best-childrens-books-the-lorax.jpg?quality=85&w=410")
# Book.create(name:"Corduroy,", author:"Don Freeman.", description:"In the middle of the night, a toy bear comes to life and hops off the shelf to replace his missing button." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/36-best-childrens-books-corduroy.jpg?quality=85&w=650")
# Book.create(name:"I Want My Hat Back", author:"Jon Klassen", description:"The witty account of a bear seeking out his lost hat; the illustrations are studded with subtle clues." , imgurl:"https://api.time.com/wp-content/uploads/2014/09/19-best-childrens-books-i-want-my-hat-back.jpg?quality=85&w=402")
# Teacher.create(name: "Mrs. Galaher Hellen")
# Teacher.create(name: "Mr. Galaher Peterson")


 puts "✅ Done seeding!"
